# Build and autotest script for f3stick sandbox
# http://travis-ci.org

language: c

addons:
  apt_packages:
    - lib32bz2-1.0
    - lib32ncurses5
    - lib32z1

before_script:
# General toolchain dependencies
  - pushd .
  - cd ~
  - wget https://launchpadlibrarian.net/186124160/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - tar -jxf gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2
  - PATH=$PATH:$HOME/gcc-arm-none-eabi-4_8-2014q3/bin
  - popd

script:
  - arm-none-eabi-gcc --version
  - make cube
  - make all

